### ISSUE TITLE
it wont work on macbook  plus ...

### ISSUE THREAD

**Issue by DavidIgor** [Crsarmv7l/TPMS-Flipper#3]
Hi , I have not managed to run it on macbook , besides what modulation will it transmit ? 
do you have any custom modulation presets ?  
thanks 
David

**Comment by DavidIgor** [comment]
if I get correct modulation will I be able to record raw (with flipper)?

**Comment by DavidIgor** [comment]
update:
Input] Test mode active. Reading samples from file: /Users/igordavid/TPMS/Output/smd3ma4.cu8
Total packets in file 1
Can't determine modulation type from header
{'version': '1', 'timescale': '1us', 'created': '2023-06-09 16:42:04+0200'}
rm: /Users/igordavid/TPMS/Output/smd3ma4.cu8: is a directory
logout

**Comment by DavidIgor** [comment]
@Crsarmv7l 
sensor ID : I have Schrader but sensor ID read with protoview are not working in your program, and when I read them with hackrf tpms app it spits out 8digit id .

**Comment by Crsarmv7l** [comment]
> @Crsarmv7l sensor ID : I have Schrader but sensor ID read with protoview are not working in your program, and when I read them with hackrf tpms app it spits out 8digit id .

You need to get the sensor id from rtl433 (which is in the readme), I only created it for linux (which is also literally in the readme to use Ubuntu), each protocol has different timings and modulations, and sure if you create a custom modulation you might be able to record raws. I had one working for pmv-107j.

Also I only implemented ONE of the schrader tpms', there are multiple.

**Comment by Crsarmv7l** [comment]
Read the readme. Almost all your questions and "issues" would have been answered
